// Copyright (c) 2022 AutonomouStuff, LLC
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef PACMOD3_CAN_IDS_H
#define PACMOD3_CAN_IDS_H

// The CAN IDs are common across all DBC versions since IDs are never re-used
// See generate_code.bash script for how these define are auto-generated

#define ACCEL_AUX_RPT_CANID (0x300)
#define ACCEL_CMD_CANID (0x100)
#define ACCEL_CMD_LIMIT_RPT_CANID (0x201)
#define ACCEL_RPT_CANID (0x200)
#define AIR_PRESSURE_RPT_CANID (0x424)
#define ANG_VEL_RPT_CANID (0x41a)
#define BRAKE_AUX_RPT_CANID (0x304)
#define BRAKE_CMD_CANID (0x104)
#define BRAKE_CMD_LIMIT_RPT_CANID (0x205)
#define BRAKE_DECEL_AUX_RPT_CANID (0x338)
#define BRAKE_DECEL_CMD_CANID (0x13c)
#define BRAKE_DECEL_RPT_CANID (0x23c)
#define BRAKE_MOTOR_RPT_1_CANID (0x401)
#define BRAKE_MOTOR_RPT_2_CANID (0x402)
#define BRAKE_MOTOR_RPT_3_CANID (0x403)
#define BRAKE_RPT_CANID (0x204)
#define CABIN_CLIMATE_CMD_CANID (0x154)
#define CABIN_CLIMATE_RPT_CANID (0x254)
#define CABIN_FAN_SPEED_CMD_CANID (0x150)
#define CABIN_FAN_SPEED_RPT_CANID (0x250)
#define CABIN_TEMP_CMD_CANID (0x14c)
#define CABIN_TEMP_RPT_CANID (0x24c)
#define COMPONENT_RPT_00_CANID (0x20)
#define COMPONENT_RPT_01_CANID (0x21)
#define COMPONENT_RPT_02_CANID (0x22)
#define COMPONENT_RPT_03_CANID (0x23)
#define COMPONENT_RPT_04_CANID (0x24)
#define CRUISE_CONTROL_BUTTONS_CMD_CANID (0x108)
#define CRUISE_CONTROL_BUTTONS_RPT_CANID (0x208)
#define DASH_CONTROLS_LEFT_CMD_CANID (0x10c)
#define DASH_CONTROLS_LEFT_RPT_CANID (0x20c)
#define DASH_CONTROLS_RIGHT_CMD_CANID (0x110)
#define DASH_CONTROLS_RIGHT_RPT_CANID (0x210)
#define DATE_TIME_RPT_CANID (0x40f)
#define DETECTED_OBJECT_RPT_CANID (0x411)
#define DOOR_RPT_CANID (0x417)
#define DRIVE_TRAIN_FEATURE_RPT_CANID (0x41f)
#define ENGINE_BRAKE_AUX_RPT_CANID (0x344)
#define ENGINE_BRAKE_CMD_CANID (0x144)
#define ENGINE_BRAKE_RPT_CANID (0x244)
#define ENGINE_RPT_2_CANID (0x425)
#define ENGINE_RPT_CANID (0x410)
#define ESTOP_RPT_CANID (0x41c)
#define EXHAUST_BRAKE_CMD_CANID (0x145)
#define EXHAUST_BRAKE_RPT_CANID (0x245)
#define GLOBAL_CMD_CANID (0x80)
#define GLOBAL_RPT_2_CANID (0x11)
#define GLOBAL_RPT_CANID (0x10)
#define HAZARD_LIGHTS_CMD_CANID (0x114)
#define HAZARD_LIGHTS_RPT_CANID (0x214)
#define HEADLIGHT_AUX_RPT_CANID (0x318)
#define HEADLIGHT_CMD_CANID (0x118)
#define HEADLIGHT_RPT_CANID (0x218)
#define HORN_CMD_CANID (0x11c)
#define HORN_RPT_CANID (0x21c)
#define INTERIOR_LIGHTS_RPT_CANID (0x416)
#define LAT_LON_HEADING_RPT_CANID (0x40e)
#define LINEAR_ACCEL_RPT_CANID (0x419)
#define MARKER_LAMP_CMD_CANID (0x148)
#define MARKER_LAMP_RPT_CANID (0x248)
#define MEDIA_CONTROLS_CMD_CANID (0x120)
#define MEDIA_CONTROLS_RPT_CANID (0x220)
#define NOTIFICATION_CMD_CANID (0x41b)
#define NOTIFICATION_RPT_CANID (0x423)
#define OCCUPANCY_RPT_CANID (0x415)
#define PARKING_BRAKE_AUX_RPT_CANID (0x324)
#define PARKING_BRAKE_CMD_CANID (0x124)
#define PARKING_BRAKE_RPT_CANID (0x224)
#define REAR_LIGHTS_RPT_CANID (0x418)
#define REAR_PASS_DOOR_CMD_CANID (0x140)
#define REAR_PASS_DOOR_RPT_CANID (0x240)
#define SAFETY_BRAKE_CMD_CANID (0xc1)
#define SAFETY_BRAKE_RPT_CANID (0x41)
#define SAFETY_FUNC_CMD_CANID (0xc0)
#define SAFETY_FUNC_CRITICAL_STOP_RPT_CANID (0x420)
#define SAFETY_FUNC_RPT_CANID (0x40)
#define SHIFT_AUX_RPT_CANID (0x328)
#define SHIFT_CMD_CANID (0x128)
#define SHIFT_RPT_CANID (0x228)
#define SOFTWARE_VERSION_RPT_00_CANID (0x408)
#define SOFTWARE_VERSION_RPT_01_CANID (0x409)
#define SOFTWARE_VERSION_RPT_02_CANID (0x40a)
#define SOFTWARE_VERSION_RPT_03_CANID (0x40b)
#define SOFTWARE_VERSION_RPT_04_CANID (0x40c)
#define SPRAYER_CMD_CANID (0x138)
#define SPRAYER_RPT_CANID (0x238)
#define STEERING_AUX_RPT_CANID (0x32c)
#define STEERING_CMD_CANID (0x12c)
#define STEERING_CMD_LIMIT_RPT_CANID (0x22d)
#define STEERING_MOTOR_RPT_1_CANID (0x404)
#define STEERING_MOTOR_RPT_2_CANID (0x405)
#define STEERING_MOTOR_RPT_3_CANID (0x406)
#define STEERING_RPT_CANID (0x22c)
#define SUPERVISORY_CTRL_CANID (0x81)
#define TIRE_PRESSURE_RPT_CANID (0x41e)
#define TURN_AUX_RPT_CANID (0x330)
#define TURN_CMD_CANID (0x130)
#define TURN_RPT_CANID (0x230)
#define USER_NOTIFICATION_CMD_CANID (0x41d)
#define VEHICLE_FAULT_RPT_CANID (0x42)
#define VEHICLE_SPEED_RPT_CANID (0x400)
#define VEH_DYNAMICS_RPT_CANID (0x413)
#define VIN_RPT_2_CANID (0x422)
#define VIN_RPT_CANID (0x414)
#define WATCHDOG_RPT_2_CANID (0x421)
#define WATCHDOG_RPT_CANID (0x600)
#define WHEEL_SPEED_RPT_2_CANID (0x426)
#define WHEEL_SPEED_RPT_CANID (0x407)
#define WIPER_AUX_RPT_CANID (0x334)
#define WIPER_CMD_CANID (0x134)
#define WIPER_RPT_CANID (0x234)
#define YAW_RATE_RPT_CANID (0x40d)

#endif  // PACMOD3_CAN_IDS_H
