#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "dbccodeconf.h"

#include "pacmod12.h"

// This version definition comes from main driver version and
// can be compared in user code space for strict compatibility test
#define VER_CUSTOMER_ECU_PACMOD12_MAJ (0U)
#define VER_CUSTOMER_ECU_PACMOD12_MIN (0U)

typedef struct
{
  GLOBAL_RPT_t GLOBAL_RPT;
  GLOBAL_RPT_2_t GLOBAL_RPT_2;
  COMPONENT_RPT_00_t COMPONENT_RPT_00;
  COMPONENT_RPT_01_t COMPONENT_RPT_01;
  COMPONENT_RPT_02_t COMPONENT_RPT_02;
  COMPONENT_RPT_03_t COMPONENT_RPT_03;
  COMPONENT_RPT_04_t COMPONENT_RPT_04;
  SAFETY_FUNC_RPT_t SAFETY_FUNC_RPT;
  SAFETY_BRAKE_RPT_t SAFETY_BRAKE_RPT;
  VEHICLE_FAULT_RPT_t VEHICLE_FAULT_RPT;
  ACCEL_RPT_t ACCEL_RPT;
  ACCEL_CMD_LIMIT_RPT_t ACCEL_CMD_LIMIT_RPT;
  BRAKE_RPT_t BRAKE_RPT;
  BRAKE_CMD_LIMIT_RPT_t BRAKE_CMD_LIMIT_RPT;
  CRUISE_CONTROL_BUTTONS_RPT_t CRUISE_CONTROL_BUTTONS_RPT;
  DASH_CONTROLS_LEFT_RPT_t DASH_CONTROLS_LEFT_RPT;
  DASH_CONTROLS_RIGHT_RPT_t DASH_CONTROLS_RIGHT_RPT;
  HAZARD_LIGHTS_RPT_t HAZARD_LIGHTS_RPT;
  HEADLIGHT_RPT_t HEADLIGHT_RPT;
  HORN_RPT_t HORN_RPT;
  MEDIA_CONTROLS_RPT_t MEDIA_CONTROLS_RPT;
  PARKING_BRAKE_RPT_t PARKING_BRAKE_RPT;
  SHIFT_RPT_t SHIFT_RPT;
  STEERING_RPT_t STEERING_RPT;
  STEERING_CMD_LIMIT_RPT_t STEERING_CMD_LIMIT_RPT;
  TURN_RPT_t TURN_RPT;
  WIPER_RPT_t WIPER_RPT;
  SPRAYER_RPT_t SPRAYER_RPT;
  BRAKE_DECEL_RPT_t BRAKE_DECEL_RPT;
  REAR_PASS_DOOR_RPT_t REAR_PASS_DOOR_RPT;
  ENGINE_BRAKE_RPT_t ENGINE_BRAKE_RPT;
  EXHAUST_BRAKE_RPT_t EXHAUST_BRAKE_RPT;
  MARKER_LAMP_RPT_t MARKER_LAMP_RPT;
  CABIN_TEMP_RPT_t CABIN_TEMP_RPT;
  CABIN_FAN_SPEED_RPT_t CABIN_FAN_SPEED_RPT;
  CABIN_CLIMATE_RPT_t CABIN_CLIMATE_RPT;
  ACCEL_AUX_RPT_t ACCEL_AUX_RPT;
  BRAKE_AUX_RPT_t BRAKE_AUX_RPT;
  HEADLIGHT_AUX_RPT_t HEADLIGHT_AUX_RPT;
  PARKING_BRAKE_AUX_RPT_t PARKING_BRAKE_AUX_RPT;
  SHIFT_AUX_RPT_t SHIFT_AUX_RPT;
  STEERING_AUX_RPT_t STEERING_AUX_RPT;
  TURN_AUX_RPT_t TURN_AUX_RPT;
  WIPER_AUX_RPT_t WIPER_AUX_RPT;
  BRAKE_DECEL_AUX_RPT_t BRAKE_DECEL_AUX_RPT;
  ENGINE_BRAKE_AUX_RPT_t ENGINE_BRAKE_AUX_RPT;
  VEHICLE_SPEED_RPT_t VEHICLE_SPEED_RPT;
  BRAKE_MOTOR_RPT_1_t BRAKE_MOTOR_RPT_1;
  BRAKE_MOTOR_RPT_2_t BRAKE_MOTOR_RPT_2;
  BRAKE_MOTOR_RPT_3_t BRAKE_MOTOR_RPT_3;
  STEERING_MOTOR_RPT_1_t STEERING_MOTOR_RPT_1;
  STEERING_MOTOR_RPT_2_t STEERING_MOTOR_RPT_2;
  STEERING_MOTOR_RPT_3_t STEERING_MOTOR_RPT_3;
  WHEEL_SPEED_RPT_t WHEEL_SPEED_RPT;
  SOFTWARE_VERSION_RPT_00_t SOFTWARE_VERSION_RPT_00;
  SOFTWARE_VERSION_RPT_01_t SOFTWARE_VERSION_RPT_01;
  SOFTWARE_VERSION_RPT_02_t SOFTWARE_VERSION_RPT_02;
  SOFTWARE_VERSION_RPT_03_t SOFTWARE_VERSION_RPT_03;
  SOFTWARE_VERSION_RPT_04_t SOFTWARE_VERSION_RPT_04;
  YAW_RATE_RPT_t YAW_RATE_RPT;
  LAT_LON_HEADING_RPT_t LAT_LON_HEADING_RPT;
  DATE_TIME_RPT_t DATE_TIME_RPT;
  ENGINE_RPT_t ENGINE_RPT;
  DETECTED_OBJECT_RPT_t DETECTED_OBJECT_RPT;
  VEH_DYNAMICS_RPT_t VEH_DYNAMICS_RPT;
  VIN_RPT_t VIN_RPT;
  OCCUPANCY_RPT_t OCCUPANCY_RPT;
  INTERIOR_LIGHTS_RPT_t INTERIOR_LIGHTS_RPT;
  DOOR_RPT_t DOOR_RPT;
  REAR_LIGHTS_RPT_t REAR_LIGHTS_RPT;
  LINEAR_ACCEL_RPT_t LINEAR_ACCEL_RPT;
  ANG_VEL_RPT_t ANG_VEL_RPT;
  ESTOP_RPT_t ESTOP_RPT;
  TIRE_PRESSURE_RPT_t TIRE_PRESSURE_RPT;
  DRIVE_TRAIN_FEATURE_RPT_t DRIVE_TRAIN_FEATURE_RPT;
  SAFETY_FUNC_CRITICAL_STOP_RPT_t SAFETY_FUNC_CRITICAL_STOP_RPT;
  WATCHDOG_RPT_2_t WATCHDOG_RPT_2;
  VIN_RPT_2_t VIN_RPT_2;
  NOTIFICATION_RPT_t NOTIFICATION_RPT;
  AIR_PRESSURE_RPT_t AIR_PRESSURE_RPT;
  ENGINE_RPT_2_t ENGINE_RPT_2;
  WHEEL_SPEED_RPT_2_t WHEEL_SPEED_RPT_2;
  WATCHDOG_RPT_t WATCHDOG_RPT;
} customer_ecu_pacmod12_rx_t;

typedef struct
{
  GLOBAL_CMD_t GLOBAL_CMD;
  SUPERVISORY_CTRL_t SUPERVISORY_CTRL;
  SAFETY_FUNC_CMD_t SAFETY_FUNC_CMD;
  SAFETY_BRAKE_CMD_t SAFETY_BRAKE_CMD;
  ACCEL_CMD_t ACCEL_CMD;
  BRAKE_CMD_t BRAKE_CMD;
  CRUISE_CONTROL_BUTTONS_CMD_t CRUISE_CONTROL_BUTTONS_CMD;
  DASH_CONTROLS_LEFT_CMD_t DASH_CONTROLS_LEFT_CMD;
  DASH_CONTROLS_RIGHT_CMD_t DASH_CONTROLS_RIGHT_CMD;
  HAZARD_LIGHTS_CMD_t HAZARD_LIGHTS_CMD;
  HEADLIGHT_CMD_t HEADLIGHT_CMD;
  HORN_CMD_t HORN_CMD;
  MEDIA_CONTROLS_CMD_t MEDIA_CONTROLS_CMD;
  PARKING_BRAKE_CMD_t PARKING_BRAKE_CMD;
  SHIFT_CMD_t SHIFT_CMD;
  STEERING_CMD_t STEERING_CMD;
  TURN_CMD_t TURN_CMD;
  WIPER_CMD_t WIPER_CMD;
  SPRAYER_CMD_t SPRAYER_CMD;
  BRAKE_DECEL_CMD_t BRAKE_DECEL_CMD;
  REAR_PASS_DOOR_CMD_t REAR_PASS_DOOR_CMD;
  ENGINE_BRAKE_CMD_t ENGINE_BRAKE_CMD;
  EXHAUST_BRAKE_CMD_t EXHAUST_BRAKE_CMD;
  MARKER_LAMP_CMD_t MARKER_LAMP_CMD;
  CABIN_TEMP_CMD_t CABIN_TEMP_CMD;
  CABIN_FAN_SPEED_CMD_t CABIN_FAN_SPEED_CMD;
  CABIN_CLIMATE_CMD_t CABIN_CLIMATE_CMD;
  NOTIFICATION_CMD_t NOTIFICATION_CMD;
  USER_NOTIFICATION_CMD_t USER_NOTIFICATION_CMD;
} customer_ecu_pacmod12_tx_t;

uint32_t customer_ecu_pacmod12_Receive(customer_ecu_pacmod12_rx_t* m, const uint8_t* d, uint32_t msgid, uint8_t dlc);

#ifdef __DEF_CUSTOMER_ECU_PACMOD12__

extern customer_ecu_pacmod12_rx_t customer_ecu_pacmod12_rx;

extern customer_ecu_pacmod12_tx_t customer_ecu_pacmod12_tx;

#endif // __DEF_CUSTOMER_ECU_PACMOD12__

#ifdef __cplusplus
}
#endif
