version: 2
jobs:
  dashing:
    docker:
      - image: autonomoustuff/docker-builds:dashing-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-add-repository -y ppa:jwhitleyastuff/kvaser-linux
            apt-get update -qq && apt-get install -qq dpkg kvaser-canlib-dev
            mkdir $CIRCLE_PROJECT_REPONAME
            mv `find -maxdepth 1 -not -name . -not -name $CIRCLE_PROJECT_REPONAME` $CIRCLE_PROJECT_REPONAME/
      - run:
          name: Install Dependencies
          command: |
            git clone https://github.com/astuff/kvaser_interface -b dashing-devel
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            cd ..
            colcon build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            cd ..
            colcon test --packages-select $CIRCLE_PROJECT_REPONAME
            colcon test-result
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - dashing
