version: 2.1

commands:
  ros_build:
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source /opt/ros/*/setup.bash
            mkdir pacmod3 && mv `find -maxdepth 1 -not -name . -not -name pacmod3` pacmod3/
            rosdep update && rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            source /opt/ros/*/setup.bash
            cd ..
            catkin build
      - run:
          name: Lint
          command: |
            cd ..
            catkin build pacmod3 --no-deps --make-args roslint
      - run:
          name: Run Tests
          command: |
            source /opt/ros/*/setup.bash
            cd ..
            catkin run_tests --no-deps pacmod3
            catkin_test_results

jobs:
  noetic:
    docker:
      - image: autonomoustuff/docker-builds:noetic-ros-base
    steps:
      - ros_build
    working_directory: ~/src

workflows:
  ros_build:
    jobs:
      - noetic
