version: 2
jobs:
  kinetic:
    docker:
      - image: autonomoustuff/docker-builds:kinetic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            cd ..
            catkin run_tests
    working_directory: ~/src

  lunar:
    docker:
      - image: autonomoustuff/docker-builds:lunar-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            cd ..
            catkin run_tests
    working_directory: ~/src

  melodic:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            cd ..
            catkin run_tests
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - kinetic
      - lunar
      - melodic
