version: 2
jobs:
  melodic:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -name setup.bash | sort | head -1`
            cd ..
            catkin run_tests --no-deps pacmod3
            catkin_test_results
    working_directory: ~/src

  melodic_devel_release:
    docker:
      - image: autonomoustuff/docker-builds:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update -qq && apt-get install fakeroot -y dh-make python-bloom ruby
            gem install --no-rdoc --no-ri deb-s3
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            bloom-generate rosdebian --os-name ubuntu --os-version bionic --ros-distro melodic
            fakeroot debian/rules binary
      - run:
          name: Upload
          command: |
            cd ../ && deb-s3 upload -b autonomoustuff-devel-qa -c bionic --preserve-versions $(ls *.deb) --access-key-id=$S3_ACCESS_KEY_ID --secret-access-key=$S3_SECRET_ACCESS_KEY
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - melodic
  aws_release:
    jobs:
      - melodic_devel_release:
          context: ubuntu-pkg-build
          filters:
            branches:
              only:
                - /maint/pacmod_msg_migration-test_release
              ignore:
                - master
                - /.*/
            tags:
              only: /^devel.*/

